### ISSUE TITLE
Could be better to add hint for how to create client cert

### ISSUE THREAD

**Issue by sunpeinju** [hcl-cwp/populate-names#2]
Good example!

One thing worth to enhance is the readme doesn't include hint for how to create client cert to run this example.

We'd better add a link to to official doc site:

https://doc.cwpcollaboration.com/appdevpack/docs/en/proton-admin.html#client-certificate-authentication

**Comment by ddelay** [comment]
Good point.  See PR #3.

**Comment by hcldan** [comment]
Fixed by #3
